# Configuration yaml
# =============================================================================
# Created By  : Ben Grodner
# Created : 9/9/22
# =============================================================================
# Configuration file for Fig 5b
# These values get loaded into the snakemake and notebook as a dictionary in the variable 'config'
# =============================================================================

## Paths
### used in the notebook
workdir: /fs/cbsuvlaminck2/workdir/bmg224/manuscripts/mgefish/code/fig_5/fig_5b/HiPRFISH
pipeline_path: ../../..  # relative path to the segmentation  pipeline folder from workdir
functions_path: functions  # Path to function scripts relative to the pipeline path

### This terminology is to adapt to the old hiprfish scripts
__default__:
  SCRIPTS_PATH: ../../../scripts/HiPRFISH
  DATA_DIR: ../../../../data/fig_5/fig_5b  # Relative path to wherever your input images are from the
  PROBE_DESIGN_DIR: ../../../../data/fig_5/HiPRFISH_probe_design_output

### Added paths that were previously hardcoded
output_dir: ../../../../outputs/fig_5/fig_5b/HiPRFISH # relative path of the directory you want to write to,
figure_dir: ../../../../outputs/fig_5/fig_5b/figures

fret_dir: ../../../../data/fig_5/HiPRFISH_fret_files
hipr_ref_dir: ../../../../data/fig_5/HiPRFISH_reference_spectra


## Inputs
### This terminology is to adapt to the old hiprfish scripts
images:
    image_list_table: hipr_input_table.csv

### new terminology
snakefilename: Snakefile
probe_design_filename: DSGN0673_primerset_C_barcode_selection_MostSimple_full_length_probes.csv

## Params
ref_train_simulations: 2000

## Filename formatting
probe_design_id: DSGN0673
reference_training:
  script: hiprfish_imaging_train_reference.py
  out_dir: reference_training
