# Configuration yaml
# =============================================================================
# Created By  : Ben Grodner
# Last edited : 4/6/22
# =============================================================================
# Configuration file for HiPRFISH_run segmentation
# These values get loaded into the snakemake as a dictionary in the variable 'config'
# =============================================================================

## Paths
workdir: /fs/cbsuvlaminck2/workdir/bmg224/manuscripts/mgefish/code/fig_3/fig_3b
input_dir: ../../../data/fig_3/fig_3b # Relative path to wherever your input images are from the
                  # projecet workdir
output_dir: ../../../outputs/fig_3/fig_3b # relative path of the directory you want to write to,
                        # does not need to exist yet
pipeline_path: ../../../../../hiprfish/image_analysis_code/pipeline_segmentation
                # relative path to the segmentation  pipeline folder from workdir
functions_path: functions  # Path to function scripts relative to the pipeline path
snakefile: Snakefile  # relative path to the snakefile

## Inputs
input_ext: _Airyscan_Processing_Stitch.czi  # Extenstion for image files
input_table_fn: input_table.csv  # path to table of input images
input_regex: '*'
input_table_cols: [sample_name]  # Add to if you want different params for
                                  # different images, one colum must be "sample_name"
conda_env: hiprfish_imaging_py38
run_fn: run.sh  # Bash script to execute and document your run command
# conda_env_fn: ../envs/hiprfish_imaging_py38.yaml  # environment filename relative
#                                                 # to the rules folder in the pipeline

## Params
cell_seg:
  fn_mod: _cell_seg  # Used in filenaming to differenitate from spot segmentation
  channels: [3]  # Indices of channels you want to follow these params
  pre_log: False  # Pre-processing: take the log? used for high signal variance
  pre_denoise: 0.025  # total variation denoising weight zero to turn off
  pre_gauss: 3  # Gaussian filter? no if zero, otherwise value sets the sigma
  diff_gauss: (0,)  # Difference of gaussians edge enhancement?...set to (0,) if not
  bg_filter: True  # Do we even want to subtract the background?
  bg_log: False  # Take the log of the image in auto background subtraction
  bg_smoothing: 3  # Pixels for gaussian blurring in auto background subtraction
  n_clust_bg: 5  # Number of clusters to use in auto background subtraction
  top_n_clust_bg: 4  # how many clusters to use as foreground in auto background subtraction
  bg_threshold: 0  # Manual value of background subtraction threshold
                  # overrides auto background subtraction
  n_clust: 2  # Number of clusters to use in LNE foreground selection (only selects the highest intensity one)
  small_objects: 50  # Remove segmented objects with pixel area smaller than this value
  maxima: False  # Locate maxima in segmentaiton and get intensities there


spot_seg:
  fn_mod: _spot_seg
  channels: [0,1,2]
  pre_log: False  # Pre-processing the segmentation image: take the log
  pre_denoise: 0  # Use denoise non-local means?
  pre_gauss: 0  # Gaussian filter? no if zero, otherwise value sets the sigma
  diff_gauss: (0,)  # Difference of gaussians edge enhancement?...set to (0,) if not
  bg_filter: True  # Do we even want to subtract the background?
  bg_log: False  # Take the log of the image in auto background subtraction
  bg_smoothing: 2  # Pixels for gaussian blurring in auto background subtraction
  n_clust_bg: 5  # Number of clusters to use in auto background subtraction
  top_n_clust_bg: 4  # how many clusters to use as foreground in auto background subtraction
  bg_threshold: 0  # Manual value of background subtraction threshold
                  # overrides auto background subtraction
  n_clust: 2  # Number of clusters to use in LNE foreground selection
  small_objects: 9  # Remove segmented objects with pixel area smaller than this value
  maxima: True  # Locate maxima in segmentaiton and get intensities there

seg_process_dpi: 10000
seg_process_ext: _process.pdf
local_max_mindist: 3
max_dist_to_cell: 5
