ref_train_simulations: 2000
__default__:
  SCRIPTS_PATH: ../../scripts/HiPRFISH
  PROBE_DESIGN_DIR: /workdir/bmg224/manuscripts/mgefish/data/HiPRFISH_probe_design

probe_design_filename: welch2016_5b_distant_lact.csv
probe_design_barcode_column: code
hipr_ref_dir: /workdir/bmg224/manuscripts/mgefish/data/unused/fig_5/HiPRFISH_reference_spectra
ref_files_fmt: 08_18_2018_enc_{}_avgint.csv  # in ref_dir, Must contain table of many cells with single fluor spectra,
fret_dir: ../../../data/HiPRFISH_fret_files
excitation_files_fmt: R{}_excitation.csv
fret_dist_min: 6 # 20bp minimum between fluors, 0.3 nm/bp so min 6nm max FRET at 10nm
fret_dist_max: 10
