# Configuration yaml
# =============================================================================
# Created By  : Ben Grodner
# Created : 9/20/22
# =============================================================================
# Configuration file for Fig 5b
# These values get loaded into the snakemake as a dictionary in the variable 'config'
# =============================================================================

## Paths
workdir: /fs/cbsuvlaminck2/workdir/bmg224/manuscripts/mgefish/code/fig_5/fig_5c
input_dir: ../../../data/fig_5/fig_5c # Relative path to wherever your input images are from the
                  # projecet workdir
output_dir: ../../../outputs/fig_5/fig_5c/HiPRFISH # relative path of the directory you want to write to,
                        # does not need to exist yet

## Params 
resolution: 0.06748  # um per pixel
