pipeline_path: /workdir/bmg224/manuscripts/mgefish/code
functions_path: functions
data_dir: /workdir/Data/bmg224/2024/brc_imaging/2024_01_10_bmgshort
laser_regex: "_2024_*.czi"
input_table_fn: hipr_input_table.csv
output_dir: ../../../outputs/bmg_plasmids_imaging/2024_01_10_bmgshort
hipr_ref_dir: /workdir/bmg224/manuscripts/mgefish/data/unused/fig_5/HiPRFISH_reference_spectra
ref_files_fmt: 08_18_2018_enc_{}_avgint.csv  # in ref_dir, Must contain table of many cells with single fluor spectra,
probe_design_dir: /workdir/bmg224/manuscripts/mgefish/data/HiPRFISH_probe_design
probe_design_filename: welch2016_5b_distant_lact.csv
ref_chan_start: 32
chan_start: 0
chan_end: 57
color_map_fn: colormap.csv  # columns are "sci_name" and "color". Must include a row with sci_name "None"
scalebar_resolution: 0.06748

# Wildcards must be 'sample_name' and 'laser'
raw_fmt: '{sample_name}.czi'
lasers: ['488','514','561','633']
shift_dir: '{sample_name}/shift_raw'
mask_dir: '{sample_name}_maskthresh_{maskthresh}_allfluor_{allfluor}/masks'
allspec_plot_dir: '{sample_name}_maskthresh_{maskthresh}_allfluor_{allfluor}/allspec_plots'
classif_dir: '{sample_name}_maskthresh_{maskthresh}_allfluor_{allfluor}/pixel_classifs'
minmax_fmt: '{sample_name}/shift_raw/{sample_name}_minmax.csv'
spec_plot_dir: '{sample_name}_maskthresh_{maskthresh}_allfluor_{allfluor}/pixel_classifs/spectra'
rgb_dir: '{sample_name}/rgbs'
rgb_done_fmt: '{sample_name}/rgbs/rgbs_done.txt'
classif_im_dir: '{sample_name}_maskthresh_{maskthresh}_allfluor_{allfluor}/classif_images'
legend_fmt: '{sample_name}_maskthresh_{maskthresh}_allfluor_{allfluor}/classif_images/{sample_name}_legend.pdf'

scripts_dir: 'scripts'

prep_script: sc_czi_file_prep.py
sum_pix_plot:
  dims: [5,3]
  dotsize: 1
m_pix_subset: 10000
shift_clips: [[0,40000],[0,40000],[0,40000],[0,30000]]


mat_classif_script: sc_matrix_classify.py


spec_plots:
  kwargs:
    lw: 0.1
    alpha: 0.5
    color: 'r'
  dims: [10,5]
  num: 100

max_shift: 1000

sigma: 3

mask_plots:
  clims: [[0,50000],[],[0,50000]]
  im_inches: 5

plot_rgb_script: sc_plot_hipr_rgb.py

rgb:
  clips: [[0,20000],[0,20000],[0,20000],[0,30000]] #clips: [[0,500000],[0,400000],[0,300000],[0,100000]]  # White and black thresholds for each laser between 0 and 1
  im_inches: 5
  exclude_lasers: ['405']
  colors: [[0,0.5,0],[0.5,0,0],[0,0,0.5],[0,0.5,0.5]]


plot_classif_script: sc_plot_hipr_classif.py

classif_im:
  clip: [0,0.2]
  im_inches: 5

allfluor:
  dims: [5,3]
  sigma: 1

laser_absent_thresholds: [0.2,0.2,0.2] # Max value relative to normalized max for declaring a laser absent

dim_spec_filt: 0.1  # filter normalized spectra with max below this value 