# Configuration yaml
# =============================================================================
# Created By  : Ben Grodner
# Created : 10/3/22
# =============================================================================
# Configuration file for Fig 5c
# These values get loaded into the snakemake and notebook as a dictionary in the variable 'config'
# =============================================================================

## Paths
### used in the notebook
pipeline_path: ../../..  # relative path to the segmentation  pipeline folder from workdir
functions_path: functions  # Path to function scripts relative to the pipeline path

### This terminology is to adapt to the old hiprfish scripts
__default__:
  SCRIPTS_PATH: ../../../scripts/HiPRFISH
  DATA_DIR: ../../../../data/fig_5/2022_12_19_hiprmegafish  # Relative path to wherever your input images are from the
  PROBE_DESIGN_DIR: ../../../../data/fig_5/HiPRFISH_probe_design_output

### Added paths that were previously hardcoded
output_dir: ../../../../outputs/fig_5/2022_12_19_hiprmegafish/HiPRFISH # relative path of the directory you want to write to,
figure_dir: ../../../../outputs/fig_5/2022_12_19_hiprmegafish/figures

fret_dir: ../../../../data/fig_5/HiPRFISH_fret_files
excitation_files_fmt: R{}_excitation.csv  # in fret dir, Must have columns [Emission, Excitation, Wavelength]
hipr_ref_dir: ../../../../data/fig_5/HiPRFISH_reference_spectra
ref_files_fmt: 08_18_2018_enc_{}_avgint.csv  # in ref_dir, Must contain table of many cells with single fluor spectra,
                                              # filename in base10 exaple 0000100 -> enc_4.csv
## Script files
snakefile_prep: Snakefile_prep


## Inputs
### This terminology is to adapt to the old hiprfish scripts
images:
    image_list_table: hipr_input_table.csv

laser_regex: '_mode_[0-9][0-9][0-9].czi'  # Must be a glob regex not re

### new terminology
snakefilename: Snakefile
probe_design_filename: welch2016_5b_no_633_channel_7bcode.csv
probe_design_barcode_column: code
barcode_color_fn: welch2016_5b_no_633_channel_colors_20230125.csv  # Goes in the PROBE_DESIGN_DIR, columns are ['barcode','color']

## Params
ref_train_simulations: 2000
fret_dist_min: 6  # 20bp minimum between fluors, 0.3 nm/bp so min 6nm,
fret_dist_max: 10  # max distance for FRET is 10nm
lasers: [488,514,561]
n_lasers: 3
ref_chan_start: 32
chan_start: 0
chan_end: 57

seg_mem_gb: 100
resource_mem_gb: 300

cell_seg:
  fn_mod: _cell_seg  # Used in filenaming to differenitate from spot segmentation
  channels: [2]  # Indices of channels you want to follow these params
  pre_log: False  # Pre-processing: take the log? used for high signal variance
  pre_denoise: 0  # total variation denoising weight zero to turn off
  pre_gauss: 3  # Gaussian filter? no if zero, otherwise value sets the sigma
  diff_gauss: (0,)  # Difference of gaussians edge enhancement?...set to (0,) if not
  bg_filter: True  # Do we even want to subtract the background?
  bg_log: False  # Take the log of the image in auto background subtraction
  bg_smoothing: 5  # Pixels for gaussian blurring in auto background subtraction
  n_clust_bg: 4  # Number of clusters to use in auto background subtraction
  top_n_clust_bg: 3  # how many clusters to use as foreground in auto background subtraction
  bg_threshold: 0  # Manual value of background subtraction threshold
                  # overrides auto background subtraction
  bg_file: 0
                # Use a premade mask for the background, overrides other code
              # Maker sure to have the "{sample}" and "{channel}"" wildcards in the string
  window: 5 # range of local neighborhood enhancement
  n_clust: 2  # Number of clusters to use in LNE foreground selection (only selects the highest intensity one)
  small_objects: 20  # Remove segmented objects with pixel area smaller than this value
  maxima: False  # Locate maxima in segmentaiton and get intensities there

seg_process_dpi: 400

rough_classifier:
  laser_0:
    channels: [3,7,11]
    lower_lim: 0.1
  laser_1:
    channels: [24, 27, 29, 31, 33]
    lower_lim: 0.2
  laser_2:
    channels: [43, 47]
    lower_lim: 0.25

n_classif_iters: 3

spec_min_thresh: 0.05  # Filter out low intensity cells
nndist_max_thresh: 0.25  # Filter out cells that are very different from the expected spectra

spectra_plots:
  axes:
    dims: [5,3]
    col: 'k'
    lw: 1
  data:
    lw: 0.01
    alpha: 0.1
    color: 'r'
  dpi: 500

nndist_plots:
  axes:
    dims: [5,3]
    col: 'k'
    lw: 1
  data:
    s: 1
    c: 'r'
    marker: '.'
  dpi: 500

seg_col_plots:
  im_inches: 5
  scalebar_resolution: 0.06748

resolution: 0.06748

## Filename formatting
probe_design_id: welch2016
reference_training:
  script: hiprfish_imaging_train_reference_5b.py
  out_dir: ../../../../outputs/fig_5/2022_12_06_restain/HiPRFISH/reference_training


clf_fmt: 'PROBEDESIGN_{}_BITS_7_NSIMS_{}_OBJ_{}'  # must have 3 curly brackets
training_data_name: training_data
training_data_neg_name: training_data_neg

prep:
  script: scripts/HiPRFISH/hiprfish_imaging_file_prep.py
  out_dir: prep

raw_fmt: 'prep/{sample_name}_las_{laser}.npy'
reg_fmt: 'prep/{sample_name}_registered.npy'
max_fmt: 'prep/{sample_name}_max.npy'
sum_fmt: 'prep/{sample_name}_sum.npy'

segmentation:
  snakefile: Snakefile_segment
  seg_in_file: sum_fmt

seg_fmt: segmentation/{sample_name}_seg.npy
seg_process_fmt: segmentation/{sample_name}_seg_process.png

seg_props_fmt: seg_props/{sample_name}_seg_props.csv

props_classif_fmt: classification/{sample_name}_props_classif.csv

plot_spec_raw_fmt: classif_plots_no_green/{sample_name}/{sample_name}_spec_avg.png
plot_spec_norm_fmt: classif_plots_no_green/{sample_name}/{sample_name}_spec_norm.png
plot_nndist_fmt: classif_plots_no_green/{sample_name}/{sample_name}_nn_dists.png
seg_col_fmt: classif_plots_no_green/{sample_name}/{sample_name}_seg_classif.npy
plot_seg_col_fmt: classif_plots_no_green/{sample_name}/{sample_name}_seg_classif.png
seg_filt_col_fmt: classif_plots_no_green/{sample_name}/{sample_name}_seg_classif_filt.npy
plot_seg_filt_col_fmt: classif_plots_no_green/{sample_name}/{sample_name}_seg_classif_filt.png
filt_summ_fmt: classif_plots_no_green/{sample_name}/{sample_name}_filt_summ.csv
classif_filt_fmt: classif_plots_no_green/{sample_name}/{sample_name}_props_classif_filt.csv
plot_classif_legend_fmt: classif_plots_no_green/{sample_name}/{sample_name}_classif_legend.png
plot_classif_filt_legend_fmt: classif_plots_no_green/{sample_name}/{sample_name}_classif_filt_legend.png
