pipeline_path: /fs/cbsuvlaminck2/workdir/bmg224/manuscripts/mgefish/code
functions_path: functions
data_dir: ../../../data/harvard_plasmid_imaging/2023_09_12_sapp05_spades08
laser_regex: "_mode_spec[45][816][841].czi"
input_table_fn: input_table.csv
output_dir: ../../outputs/matrix_classify_pipeline
hipr_ref_dir: /fs/cbsuvlaminck2/workdir/bmg224/manuscripts/mgefish/data/unused/fig_5/HiPRFISH_reference_spectra
ref_files_fmt: 08_18_2018_enc_{}_avgint.csv  # in ref_dir, Must contain table of many cells with single fluor spectra,
probe_design_dir: /fs/cbsuvlaminck2/workdir/bmg224/manuscripts/mgefish/data/unused/fig_5/HiPRFISH_probe_design_output
probe_design_filename: welch2016_5b_distant.csv
ref_chan_start: 32
chan_start: 0
chan_end: 57
color_map_fn: code/colormap.csv
scalebar_resolution: 0.06748

# Wildcards must be 'sample_name' and 'laser'
raw_fmt: '{sample_name}_mode_spec{laser}.czi'
lasers: ['488','514','561']
shift_dir: '{sample_name}_maskthresh_{maskthresh}_allfluor_{allfluor}/shift_raw'
mask_dir: '{sample_name}_maskthresh_{maskthresh}_allfluor_{allfluor}/masks'
classif_dir: '{sample_name}_maskthresh_{maskthresh}_allfluor_{allfluor}/pixel_classifs'
minmax_fmt: '{sample_name}_maskthresh_{maskthresh}_allfluor_{allfluor}/{sample_name}_minmax.csv'
spec_plot_dir: '{sample_name}_maskthresh_{maskthresh}_allfluor_{allfluor}/pixel_classifs/spectra'

scripts_dir: 'scripts'
mat_classif_script: sc_matrix_classify.py

spec_plots:
  kwargs:
    lw: 0.1
    alpha: 0.5
    color: 'r'
  dims: [10,5]
  num: 100

max_shift: 500

sigma: 3

mask_plots:
  clims: [[0,50000],[],[0,50000]]
  im_inches: 5